openapi: 3.0.0
info:
  description: |
    API for API backoffice management.
    © 2023, Telefonica.
    All rights reserved.
  title: CAPIF_API_Backoffice_Management_API
  version: 1.2.0-alpha.2
servers:
- url: '{apiRoot}/api-backoffice-management/v1'
  variables:
    apiRoot:
      default: https://example.com
paths:
  /invokers:
    get:
      description: Get all invokers registered in CAPIF.
      operationId: get_invokers
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Invokers'
          description: Invokers retrieved successfully.
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Bad request
        "401":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
        "404":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
        "411":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Length Required
        "413":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Payload Too Large
        "415":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unsupported Media Type
        "429":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Too Many Requests
        "500":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Internal Server Error
        "503":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Service Unavailable
        default:
          description: Generic Error
    x-openapi-router-controller: api_backoffice_management.controllers.default_controller
  /providers:
    get:
      description: Get all invokers registered in CAPIF.
      operationId: get_invokers
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Invokers'
          description: Invokers retrieved successfully.
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Bad request
        "401":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
        "404":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
        "411":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Length Required
        "413":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Payload Too Large
        "415":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unsupported Media Type
        "429":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Too Many Requests
        "500":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Internal Server Error
        "503":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Service Unavailable
        default:
          description: Generic Error
    x-openapi-router-controller: api_backoffice_management.controllers.default_controller
  /securityContext/{onboardingId}:
    get:
      description: Get all invokers registered in CAPIF.
      operationId: get_invokers
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvokersRegistered'
          description: Invokers retrieved successfully.
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Bad request
        "401":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
        "404":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
        "411":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Length Required
        "413":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Payload Too Large
        "415":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unsupported Media Type
        "429":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Too Many Requests
        "500":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Internal Server Error
        "503":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Service Unavailable
        default:
          description: Generic Error
    x-openapi-router-controller: api_backoffice_management.controllers.default_controller
  /service/{apfId}:
    get:
      description: Get all invokers registered in CAPIF.
      operationId: get_invokers
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Invokers'
          description: Invokers retrieved successfully.
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Bad request
        "401":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
        "404":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
        "411":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Length Required
        "413":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Payload Too Large
        "415":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unsupported Media Type
        "429":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Too Many Requests
        "500":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Internal Server Error
        "503":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Service Unavailable
        default:
          description: Generic Error
    x-openapi-router-controller: api_backoffice_management.controllers.default_controller
  /events/{subscriberId}:
    get:
      description: Get all invokers registered in CAPIF.
      operationId: get_invokers
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvokersRegistered'
          description: Invokers retrieved successfully.
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Bad request
        "401":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
        "404":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
        "411":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Length Required
        "413":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Payload Too Large
        "415":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unsupported Media Type
        "429":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Too Many Requests
        "500":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Internal Server Error
        "503":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Service Unavailable
        default:
          description: Generic Error
    x-openapi-router-controller: api_backoffice_management.controllers.default_controller
components:
  schemas:
    Invokers:
      description: Invokers registered in CAPIF.
      example:
        apiInvokerPublicKey: apiInvokerPublicKey
        onboardingSecret: onboardingSecret
        apiInvokerCertificate: apiInvokerCertificate
      properties:
        notificationDestination:
          title: notificationDestination
          type: string
        supportedFeatures:
          title: supportedFeatures
          type: string
        apiInvokerInformation:
          title: apiInvokerInformation
          type: string
        websocknotifconfig:
          title: websockNotifConfig
          type: object
          properties:
            requestWebsocketUri:
              title: requestWebsocketUri
              type: string
            websocketUri:
              title: websocketUri
              type: string
        onboardingInformation:
          title: onboardingInformation
          type: object
          properties: 
            apiInvokerPublicKey:
              title: apiInvokerPublicKey 
              type: string      
        requestTestNotification:    
          title: requestTestNotification    
          type: string
      required:
      - apiInvokerPublicKey
      - supportedFeatures
      - apiInvokerInformation
      - websockNotifConfig
      - onboardingInformation
      - requestTestNotification
    SecurityContext:
    Events:
    ProblemDetails:
      description: Represents additional information and details on an error response.
      properties:
        type:
          description: string providing an URI formatted according to IETF RFC 3986.
          title: notificationDestination
          type: string
        title:
          description: A short, human-readable summary of the problem type. It should
            not change from occurrence to occurrence of the problem.
          title: title
          type: string
        status:
          description: The HTTP status code for this occurrence of the problem.
          title: status
          type: integer
        detail:
          description: A human-readable explanation specific to this occurrence of
            the problem.
          title: detail
          type: string
        instance:
          description: string providing an URI formatted according to IETF RFC 3986.
          title: notificationDestination
          type: string
        cause:
          description: A machine-readable application error cause specific to this
            occurrence of the problem. This IE should be present and provide application-related
            error information, if available.
          title: cause
          type: string
        invalidParams:
          description: Description of invalid parameters, for a request rejected due
            to invalid parameters.
          items:
            $ref: '#/components/schemas/InvalidParam'
          minItems: 1
          title: invalidParams
          type: array
        supportedFeatures:
          description: A string used to indicate the features supported by an API
            that is used as defined in clause 6.6 in 3GPP TS 29.500. The string shall
            contain a bitmask indicating supported features in hexadecimal representation
            Each character in the string shall take a value of "0" to "9", "a" to
            "f" or "A" to "F" and shall represent the support of 4 features as described
            in table 5.2.2-3. The most significant character representing the highest-numbered
            features shall appear first in the string, and the character representing
            features 1 to 4 shall appear last in the string. The list of features
            and their numbering (starting with 1) are defined separately for each
            API. If the string contains a lower number of characters than there are
            defined features for an API, all features that would be represented by
            characters that are not present in the string are not supported
          pattern: ^[A-Fa-f0-9]*$
          title: SupportedFeatures
          type: string
      title: ProblemDetails
      type: object